spring.application.name=ProyectoTR100124
spring.datasource.url=jdbc:mysql://localhost:3306/tripelsalvador?serverTimezone=America/El_Salvador
spring.datasource.username=root
spring.datasource.password=TR100124

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true